complaint/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('all_complaints', views.all_complaints_view, name='all_complaints_view'),
    path('vote', views.add_vote, name='vote'),
    path('remove_vote', views.remove_vote, name='remove_vote'),
    path('login', views.login_view, name='login'),
    path('', views.login_view, name='login'),
    path('logged-out', views.logging_out_view, name='logout'),
    path('signup', views.sign_up_view, name='signup'),
    path('complaint/<int:id>', views.view_complaint_byid, name='view_complaint'),
    path('edit/<int:id>',views.edit_complaint_byid,name='edit_complaint'),
    path('edit/<int:id>',views.edit_complaint_byid,name='edit_dialog'),
    path('delete/<int:cmp_id>', views.delete_complaint_byid, name='delete_complaint')
]

cts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('djangoadmin/', admin.site.urls),
    path('admin/',include('complaint.admin_urls')),
    path('', include('complaint.urls')),
    path('user/',include('complaint.user_urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

complaint/models.py
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

CATEGORY_CHOICES = [
    ('academic','Academic'),
    ('mess', 'Mess'),
    ('sports', 'Sports'),
    ('student_affairs', 'Student affairs'),
    ('hostel', 'Hostel'),
    ('security', 'Security'),
    ('guest_house', 'Guest House'),
    ('library', 'Library'),
    ('other', 'Other'),
]

BRANCH_CHOICES = [
    ('cse','cse'),
    ('ece','ece'),
    ('eee','eee'),
    ('civil','civil'),
    ('mech','mech'),
    ('mme','mme'),
    ('chemical','chemical'),
    ('biotech','biotech'),
    ('none', 'none')
]

STATUS_CHOICES = [
    ('reported', 'Reported'),
    ('in_progress', 'In Progress'),
    ('completed', 'Completed'),
    ('closed', 'Closed')
]

class Complaint(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=400)
    description = models.TextField()
    id = models.AutoField(primary_key=True)
    is_anonymous= models.BooleanField(default=False)
    photo = models.ImageField(null=True, default=None,)
    branch = models.CharField(max_length=10, choices=BRANCH_CHOICES, default='none')
    
    status = models.CharField(
        max_length=15,
        choices=STATUS_CHOICES,
        default='reported',
    )
    category = models.CharField(
        max_length=18,
        choices=CATEGORY_CHOICES,
        default='other',
    )
    created_date = models.DateTimeField(default=timezone.now)

    def register(self):
        self.created_date = timezone.now()
        self.save()
    
    def __str__(self):
        return self.title

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    is_admin = models.BooleanField(default=False)
    head_of = models.CharField(
        max_length=18,
        choices = CATEGORY_CHOICES,
        default = ''
    )

class Remark(models.Model):
    text = models.TextField()
    date = models.DateField(default=timezone.now)
    complaint = models.ForeignKey(Complaint, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

class Vote(models.Model):
    vote = models.SmallIntegerField(choices=[
        (1, 'upvote'),
        (-1, 'downvote'),
    ])
    complaint = models.ForeignKey(Complaint, on_delete=models.CASCADE)
    voter = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

complaint/forms.py
from django import forms
from .models import Complaint
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
class RegisterComplaintForm(forms.ModelForm):
    photo = forms.ImageField(allow_empty_file=True,
                             required=False,)
    class Meta:
        model = Complaint
        fields = ('title', 'description', 'category', 'photo', 'branch')

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

complaint/views.py
from django.shortcuts import render
from .models import (
    Complaint, Remark, BRANCH_CHOICES,
    CATEGORY_CHOICES, STATUS_CHOICES,
    Profile, Vote,
)
from django.utils import timezone
from django.contrib.auth import authenticate, login,logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .decorators import unauthenticated_user, admin_only,allow_user
from .forms import RegisterComplaintForm, UserRegistrationForm
from django.db.models import Q
from django.core.mail import send_mail
from cts.settings import EMAIL_HOST_USER

@login_required(login_url='login')
@admin_only
def admin_view_complaints(request):
    complaints = Complaint.objects.filter(~Q(status = 'closed')).order_by('created_date')
    filter_by = request.GET.get('filter_by_category')
    if(request.user.profile.head_of != 'other' and request.user.profile.head_of != ''):
        complaints = Complaint.objects.filter(~Q(status = 'closed'), ~Q(status = 'comlpeted'),category=request.user.profile.head_of)
    show_back_btn = False
    if filter_by in [i[0] for i in CATEGORY_CHOICES]:
        show_back_btn = True
        complaints=Complaint.objects.filter(~Q(status = 'closed'), category=filter_by)
    zero_complaints=complaints.count() == 0
    return render(request, 'complaint/complaints_table.html',
                  context={'complaints': complaints , 'is_admin': True,
                           'zero_complaints':zero_complaints, 'home_header':'active',
                           'view_url': reverse('admin_complaints_view'),
                           'show_back_btn': show_back_btn})

@login_required(login_url='login')
def user_view_complaints(request):
    log_in_user = User.objects.filter(username=request.user.username).first()
    total_complaints=Complaint.objects.filter(author=log_in_user).count()
    total_pending=Complaint.objects.filter(status='in_progress',author=log_in_user).count()
    total_closed=Complaint.objects.filter(status='closed',author=log_in_user).count()
    complaints = Complaint.objects.filter(author=log_in_user).order_by('created_date')
    filter_by = request.GET.get('filter_by_category')
    if filter_by in [i[0] for i in CATEGORY_CHOICES]:
        complaints=Complaint.objects.filter(category=filter_by,author=log_in_user)
    no_of_complaints=len(complaints)
    return render(request, 'complaint/complaints_table.html',
                  context={'complaints': complaints, 'is_user': True, 'complaint_count': total_complaints,
                  'total_pending':total_pending, 'total_closed':total_closed, 
                  'user_name':log_in_user, 'no_of_complaints':no_of_complaints,
                 'home_header':'active', 'view_url': reverse('user_complaints_view')})

@login_required(login_url='login')
def all_complaints_view(request):
    complaints = Complaint.objects.filter().order_by('-created_date')
    print(request.GET)
    
    category = request.GET.get('category')
    print(category)
    if category in [i[0] for i in CATEGORY_CHOICES]:
        complaints=complaints.filter(category=category)
       

    branch = request.GET.get('branch')
    if branch in [i[0] for i in BRANCH_CHOICES]:
        complaints = complaints.filter(branch=branch)

    status = request.GET.get('status')
    if status in [i[0] for i in STATUS_CHOICES]:
        complaints = complaints.filter(status=status)

    is_admin = request.user.profile.is_admin
    
    return render(request, 'complaint/complaints_table.html', context={
                  'complaints': complaints,
                  'all_complaints': True,
                  'all_complaints_header': 'active',
                  'is_admin':is_admin,
                  })


@login_required(login_url='login')
def logging_out_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('login'))

@login_required(login_url='login')
def view_complaint_byid(request, id):
    complaint = Complaint.objects.filter(id=id)[0]
    if request.method == "POST":
        status = request.POST.get('status')
        comment = request.POST.get('comment')
        if status is not None:
            complaint.status = status
            complaint.save()
        # complaint_url = request.build_absolute_uri(reverse('view_complaint',kwargs={'id':complaint.id}))
        # email_subject = 'Your complaint at cts NIT Andhra got a remark.'
        # email_content = f'Hi {complaint.author},\n Your complaint got the following remark\n'
        # email_content += remark + '\nclick the following link to view you complaint in cts' + complaint_url
        # email_recipient = complaint.author.email
        # send_mail(email_subject, email_content, EMAIL_HOST_USER, [email_recipient], fail_silently=False)
        if comment is not None:
            Remark.objects.create(text=comment, complaint=complaint,
                               author=request.user)
        

    remarks = Remark.objects.filter(complaint=complaint)
    return render(request, 'complaint/view_complaint.html',
                  {'complaint': complaint, "comments": remarks,
                   'status_choices': STATUS_CHOICES})

def delete_complaint_byid(request, cmp_id):
    # This should be done using a post request. time issues
    complaint = Complaint.objects.filter(id=cmp_id)[0]
    complaint.delete()
    return HttpResponseRedirect(reverse('user_complaints_view'))

    
@unauthenticated_user
def login_view(request):
    if(request.method == 'POST'):
        username = request.POST.get("username")
        password = request.POST.get("password")
        is_admin = request.POST.get("is_admin")
        user = authenticate(username=username, password=password)
        if user:
            
            if is_admin =='on' or user.profile.is_admin:
                if user.profile.is_admin:
                    login(request,user)
                    return HttpResponseRedirect(reverse('all_complaints_view'))
                else:
                    return render(request, 'complaint/login.html', {'not_admin': True}) 
            
            else:
                login(request,user)
                return HttpResponseRedirect(reverse('user_complaints_view'))

        else:
            return render(request, 'complaint/login.html', {'login_fail' :True})

    return render(request, 'complaint/login.html')

@login_required(login_url='login')
def change_password_view(request):
    if(request.method =='POST'):
        old_password = request.POST.get("old_pass")
        new_password1 = request.POST.get("new_pass1")
        new_password2 = request.POST.get("new_pass2")
        if new_password1==new_password2:
            user =authenticate(username= request.user.username, password = old_password)
            if user:
                request.user.set_password(new_password1)
                request.user.save()
                user = authenticate(username= request.user.username, password = new_password1)
                if user:
                    login(request, user)
                    return render(request, 'complaint/change_password.html', context={
                        "pass_changed": True, 'password_header': 'active'
                    })
            else:
                return render(request, 'complaint/change_password.html', context={
                        "old_pass_wrong": True, 'password_header': 'active'
                    })
        else:
            return render(request, 'complaint/change_password.html', context={
                        "pass_mismatch": True, 'password_header': 'active'
                    })

    return render(request, 'complaint/change_password.html',
                  {'password_header': 'active'})


@unauthenticated_user
def sign_up_view(request):
    form=UserRegistrationForm(request.POST)
    if request.method=='POST':
        if form.is_valid():
            user=form.save()
            login(request,user)
            return HttpResponseRedirect(reverse('user_complaints_view'))
        return HttpResponse("Invalid sign up")

    return render(request, 'complaint/sign_up.html', {'form': form})

@login_required(login_url='login')
def register_complaint_page(request):
    if(request.method == 'POST'):
        form = RegisterComplaintForm(request.POST, request.FILES)
        is_anonymous=request.POST.get("is_anonymous")
        photo = request.POST.get("photo")
        if form.is_valid():
            complaint = form.save(commit=False)
            complaint.author = request.user
            complaint.photo = form.cleaned_data['photo']
            # mail_subject = f'cts: {complaint.title}'
            # recipient_profiles = Profile.objects.filter(head_of=complaint.category)
            # recipient_emails = []
            # for user_profile in recipient_profiles:
            #     recipient_emails += [user_profile.user.email]
            #complaint.photo.save(name=request.POST.get("title")+".png", content="jhkj")
            #complaint.photo.name = str(complaint.id) + ".png"
            if is_anonymous :
                complaint.is_anonymous = True
                complaint.save()
                return render(request, 'complaint/register_complaint.html',
                   context={"form_saved": True,
                             "register_header": 'active'})
            else:
                complaint.save()
                # complaint_url = request.build_absolute_uri(reverse('view_complaint',kwargs={'id':complaint.id}))
                # mail_content = f'New complaint is registered by {complaint.author}. click the following link to go to complaint.\n {complaint_url}'
                # send_mail(mail_subject, mail_content, EMAIL_HOST_USER,recipient_emails, fail_silently=False)
                return render(request, 'complaint/register_complaint.html',
                   context={"form_saved": True,

complaint/templates/complaint/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}Complaint Tracking System{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css"
    />
    <!-- Latest compiled and minified CSS -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="../../static/css/copy_link_style.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/sorting.css' %}" />
    <link rel="stylesheet" href="{% static 'css/complaint_style.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    {% block css %}
    <link rel="stylesheet" href="{% static 'css/admin.css' %}" />
    {% endblock %}

    <style>
      #footer1 {
      position: fixed;
      height: 50px;
      background-color: black;
      bottom: 0px;
      left: 0px;
      right: 0px;
      margin-bottom: 0px;
      color: white;
      font-weight: bold;
    }
    #flabel{
      padding-top: 10px;;
    }
    </style>
  </head>

  <body>
    <div class="navbar">
      <a href="{% url 'logout' %}"><i class="fa fa-fw fa-user"></i> Logout</a>
      <a href="{% url 'change-password' %}" class="{{ password_header }}"
        ><i class="fa fa-gear"></i> Change Password</a
      >

      {% if request.user.profile.is_admin %}
      <a href="{% url 'all_complaints_view' %}" class="{{ home_header }}"
        ><i class="bi bi-inbox-fill"></i> All Complaints</a
      >
      {% else %}
      <a href="{% url 'register_complaint' %}" class="{{ register_header }}"
        ><i class="fa fa-fw fa-envelope"></i> Register</a
        >
        
        <a href="{% url 'user_complaints_view' %}" class="{{ home_header }}"
        ><i class="bi bi-inbox-fill"></i> My Complaints</a
        >
        <a href="{% url 'all_complaints_view' %}" class="{{ all_complaints_header }}"
        ><i class="bi bi-inboxes-fill"></i> all Complaints</a
        >
        {% endif %}
      <span class="welcome-txt">Welcome {{ request.user.username }}!!</span>
    </div>

    {% block content %} {% endblock %} {% block footer %}
    <div class="footer">
      <p id='footer1'><label id='flabel'>&copy;Copyrights Dinesh, chaitanya, Sai Kumar.</label></p>
    </div>
    {% endblock %}
  </body>
</html>

complaint/templates/complaint/change_password.html
{% extends 'complaint/base.html' %}
{% block title %} Login : CTS{% endblock %}
{% block content %}
	<div class="container">
		<div class="left"></div>
		<div class="right" style="margin-right: 25%;"><br><br>
			<div class="formbox-cng-pass">
				<form method="post" action="{% url 'change-password' %}">
                    {% csrf_token %}
					<p><b>Old password</p>
                    <input type="password" name="old_pass" placeholder="old password">
                    <p>New Password</p>
                    <input type="password" name="new_pass1" placeholder="new password">
                    <p>Confirm Password</p>
					<input type="password" name="new_pass2" placeholder="confirm password">
                    <p></p>
                    
                    {% if old_pass_wrong %}
                    <p>oops! your old password is wrong</p>
                    {% endif %}
                    {% if pass_mismatch %}
                    <p>passwords doesnot match</p>
                    {% endif %}
					<button class="cng-pass-btn" style='background-color: rgb(90, 245, 90);' type="submit" name="" value= "change password">Change Password</button>
                </form>
                {% if pass_changed %}
                    <p>you have succcesfully changed password</p>
                    <button onclick="location.href= \"{% url 'login' %}\" ">Home</button>
                    {% endif %}
                
			</div>
		</div>
		</div>
{% endblock %}

complaint/templates/complaint/dialog.html
{% extends 'complaint/base.html' %}

{% block css %}
<style>
body {font-family: Arial, Helvetica, sans-serif;}
* {box-sizing: border-box;}

/* Set a style for all buttons */
button {
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;
}

button:hover {
  opacity:1;
}

/* Float cancel and delete buttons and add an equal width */
.cancelbtn, .deletebtn {
  float: left;
  width: 50%;
}

/* Add a color to the cancel button */
.cancelbtn {
  background-color: #ccc;
  color: black;
}

/* Add a color to the delete button */
.deletebtn {

  background-color: #f44336;
}

/* Add padding and center-align text to the container */
.container {
 padding:16px;
  text-align: center;
}

/* The Modal (background) */
.modal {
  display: none; /* Hidden by default */
  position: fixed; /* Stay in place */
  z-index: 1; /* Sit on top */
  left: 0;
  top: 0;
  width: 100%; /* Full width */
  height: 100%; /* Full height */
  overflow: auto; /* Enable scroll if needed */
  background-color:grey;
  padding-top: 50px;
}

/* Modal Content/Box */
.modal-content {
  background-color: #fefefe;
  margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
  border: 1px solid #888;
  width: 80%; /* Could be more or less, depending on screen size */
}

/* Style the horizontal ruler */
hr {
  border: 1px solid #f1f1f1;
  margin-bottom: 25px;
}
 
/* The Modal Close Button (x) */
.close {
  position: absolute;
  right: 35px;
  top: 15px;
  font-size: 40px;
  font-weight: bold;
  color: #f1f1f1;
}

.close:hover,
.close:focus {
  color: #f44336;
  cursor: pointer;
}

/* Clear floats */
.clearfix::after {
  
  content: "";
  clear: both;
  display: table;
}

/* Change styles for cancel button and delete button on extra small screens */
@media screen and (max-width: 300px) {
  .cancelbtn, .deletebtn {
     width: 100%;
  }
}
</style>
{% endblock %}
<body>
<!--
<h2>Delete Modal</h2>

 <button onclick="document.getElementById('id01').style.display='block'">Open Modal</button>
 
--> 

<div id="id01" class="modal">
  <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
  <form class="modal-content" action="/action_page.php">
    <div class="container">
      <h1>Delete Account</h1>
      <p>Are you sure you want to delete your account?</p>
    
      <div class="clearfix">
        <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
        <button class="deletebtn" type="submit" value="submit">Update</button>
      </div>
    </div>
  </form>
</div>

<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>

</body>
</html>

complaint/templates/complaint/logout.html
{% extends 'complaint/loggedout_base.html' %}
{% block content %}
<h1><b>Logout is successful.</h1>
<a  id="atag" href="{% url 'login' %}">Login</a>
<a  id="atag" href="{% url 'signup' %}">Register</a>
{% endblock %}

complaint/templates/complaint/register_complaint.html
{% extends 'complaint/base.html' %}

{% block css %}
<style>
    * {
    box-sizing: border-box;
  }
  .navbar {
    width: 100%;
    background-color: #1e5e77;
    overflow: auto;
    line-height: 50px;
  }
 
  .navbar a {
    float: right;
    padding: 12px;
    color: white;
    text-decoration: none;
    font-size: 20px;
  }
 
  .navbar a:hover {
    background-color: black;
  }
 
  .active {
    background-color: slategrey;
  }
 
  @media screen and (max-width: 500px) {
    .navbar a {
      float: none;
      display: block;
    }
  }
 
  body {
    font-family: Arial, Helvetica, sans-serif;
    margin: 0;
  }
 
  .complaint {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 70%;
    position:relative;
    left:15%;
  }
 
  .complaint td, .complaint th {
    border: 1px solid #ddd;
    padding: 8px;
  }
  .complaint tr:nth-child(even){background-color: #f2f2f2;}
 
  .complaint tr:hover {background-color: #ddd;}
 
  .complaint th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: #4caf50;
    color: white;
    cursor: pointer;
  }

  /* register complaint css */
  body{
    margin:0;
    padding:0;
    background:none;
    font-family:sans-serif;
    }
   

    ul {
    list-style-type: none;
     
    padding: 12px;
       color: white;
       text-decoration: none;
       font-size: 17px;
    }
   
    li{
    float:left;
    }
   
    .comp{
    font-size:30px;
    }
   
    .navbar a {
      float: right;
      padding: 12px;
      color: white;
      text-decoration: none;
      font-size: 20px;
    }
   
    .navbar a:hover {
      background-color: black;
    }
   
    @media screen and (max-width: 500px) {
      .navbar a {
        float: none;
        display: block;
      }
    }


    .hide-remarks-border{
      border-radius: 0%;
      border: white;
    }
    form{
      font-size: 20px;
      border:1px;
      box-shadow:5px 10px 8px #888888;
    }
    .reg-complaint{
      padding-left: 5%;
      padding-bottom: 3%;
    }
   
    .formbox{
    align-items: center;
    width:100%;
    height: 100%;
    box-sizing: border-box;
    background:white;
    box-shadow:1px 10px 40px rgba(0,0,0,.5);
   
    }
   
    .formbox input[type="text"],
    .formbox input[type="password"]
    {
    border:none;
    border-bottom: 1px solid black;
    outline:none;
    height:40px;
   
    }

#filter-category {
  width:100% !important;
}
    button {
      background-color: #4caf50;
      color: white;
      padding: 14px 20px;
      margin: 8px 0;
      border: none;
      cursor: pointer;
      width: 20%;
    }
   .sub-reg{
     font-size: large;
     margin-left: 70%;
   }
    button:hover {
      opacity: 0.8;
    }
    .formbox input[type="submit"]
{
  border:none;
  border-radius: 4px;
  outline:none;
  width: 30%;
 
  height:40px;
  color:#fff;
  background:black;
  cursor:pointer;
}

.footer{
    position: absolute;
    left:0;
    bottom:0;
    text-align: center;
    margin: 0% 40%;
    color: black;
  }

.formbox input[type="submit"]:hover
{
  background:#4CAF50;
}
.formbox label{
  font-weight: bold;
}
.container
{
  border-radius: 10px;
  
  background:white;
  margin:0 auto;
  border:2px solid #fff;
  box-shadow:0 15px 40px rgba(250,250,250,0);
 
}

h3{
  margin-top: 1px;
  text-align:center;
  font-size:30px;
  color: black;
}

.welcome-txt {
  font-size: 20px;
  color: white;
  padding-top:3%;
  margin: 0px;
}


.title{
  text-align:center;
  padding:0px 0 20px;
  font-size:200%;
  }
  .container{
    font-family: serif;
  }


.example-print {
  display: none;
}
@media print {
 .example-screen {
     display: none;
  }
  .example-print {
     display: block;
  }
  #ta{
    resize:none;
  }

</style>
{% endblock %}
{% block content %}

<div class ="container" style='margin-bottom: 50%;'>
<div class="left"></div>
<div class="right">
  <br>
  {% if edit %}
   <div class="title"><b>Edit complaint.</b></div>
  {% else %}
   <div class="title"><b>Register complaint/request.</b></div>
  {% endif %}
<br><br>
<div class="formbox">
<br><br><br>
{% if form_saved %}
<p>complaint registered! File another complaint below.</p>
{% endif %}
<form class="reg-complaint" method="post" action="{% url 'register_complaint' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="typ"><b>Type of complaint:</b></label>
  <select id="comp" name="category">
    <option value="academic">Academics</option>
    <option value="mess">Mess</option>
    <option value="sports">Sports</option>
    <option value="student_affairs">Student affairs</option>
    <option value="hostel">Hostel</option>
    <option value="security">Security</option>
    <option value="guest_house">Guest House</option> 
    <option value="library">Library</option>
    <option value="other">Other</option>
  </select>
  <br></br>
<label for="myCheck">Choose branch:</label> 
<input type="checkbox" id="myCheck" onclick="myFunction()">
<br><br>
<div id="text" style="display:none">
  <select name="branch" id="branch" >
    <option value="none">None</option>
    <option value="cse">Cse</option>
    <option value="ece">Ece</option>
    <option value="eee">Eee</option>
    <option value="civil">Civil</option>
    <option value="mech">Mechanical</option>
    <option value="mme">Mme</option>
    <option value="chemical">Chemical</option>
    <option value="biotech">Biotech</option>

  </select>
 </div>
<br></br>
<label for="des">Description :</label><br></br>
{% if edit %}
 <input type="text" name="title" placeholder="enter subject" value={{ complaint.title }} required><br><br>
 <textarea id="ta" cols="45" rows="3" placeholder="describe.."  style="resize: none;">{{ complaint.description }}</textarea>
 {% else %}
 <input type="text" name="title" placeholder="enter subject" required><br><br>
 <textarea id="ta" cols="45" rows="3" placeholder="describe.." name="description" style="resize: none;"></textarea>
 
{% endif %}
<br>
<label for="id_photo">Photo:</label> <input type="file" name="photo" accept="image" id="id_photo">
<br></br>
{% if invalid_form %}<p>Invalid form. Try again!</p>{% endif %}
{% if edit %}
  <a class="sub-reg" href='{% url 'edit_dialog' complaint.id %}'" type="" name="" value= "submit">Update</a>

{% else %}
 <button class="sub-reg" type="submit" name="" value= "submit">Submit</button>
{% endif %}
</form>
</div>
</div>
</div>
<script>
function myFunction() {
  var checkBox = document.getElementById("myCheck");
  var text = document.getElementById("text");
  if (checkBox.checked == true){
    text.style.display = "block";
  } else {
     text.style.display = "none";
  }
}
</script>
{% endblock %}